export const brands = [
    "Kellogg’s",
    "Wingreens Farms",
    "Dabur",
    "Hellmann’s",
    "Veeba",
    "Nutella",
    "Dr.Oetker",
    "Patanjali",
    "Bagrrys",
    "Organic India",
    "Saffola",
    "MyFitness",
    "FitFeast",
    "Pintola",
    "Slurrp Farm",
    "Sundrop",
    "Farmley",
    "Safal",
    "iD",
    "Tetley",
    "Sleepy Owl",
    "Zenma Coffee",
    "Teabox",
    "Wonderland Foods",
    "Nutraj",
    "Organic Tattva",
    "Open Secret",
    "Tata Sampann",
    "Nourish You",
    "Tata Soulfull",
    "Yoga Bar",
    "Kissan",
    "Tops",
    "Ching’s Secret",
    "Del Monte",
    "Maggi",
    "Knorr",
    "MasterChow",
    "MuscleBlaze",
    "True Elements",
    "Quaker",
    "Hershey’s",
    "Lotus Biscoff",
    "Zandu",
    "Mapro",
    "Apis",
    "Aplenty",
    "Bambino",
    "Haldiram’s",
    "Nissin",
    "Gits",
    "MTR",
    "Hocco",
    "Amul",
    "Nestlé",
    "Aptamil",
    "Similac",
    "Weikfield",
    "Betty Crocker",
    "Pillsbury",
    "Taj Mahal",
    "Horlicks",
    "Protinex",
    "Ensure",
    "Complan",
    "Pukka",
    "Girnar",
    "Chaayos",
    "Society",
    "Blue Tokai",
    "Dorje Teas",
    "4700BC",
    "Tropicana",
    "Maaza",
    "Frooti",
    "Slice",
    "Hamdard",
    "Baidyanath",
    "Nutralite",
    "Urban Platter",
    "St. Dalfour",
    "Eastern",
    "Daawat",
    "Kohinoor",
    "Happilo",
    "Borges",
    "Kikkoman",
    "Thai Kitchen",
    "French’s",
    "American Garden",
    "Ragu",
    "Sakura",
    "Al Ameera",
    "Batchelors",
    "9 AM",
    "The Baker's Dozen",
    "NOTO",
    "Disano",
    "Alpino",
    "BeastLife",
    "I'MWOW",
    "Nutty American",
    "Shrego",
    "Skippy",
    "Chase Protein",
    "Mangat Ram",
    "Rajdhani",
    "Aravalli",
    "GM Foods",
    "Pansari",
    "Mugdh",
    "RiteBite",
    "Harnik",
    "Kwality",
    "ME & MILLETS",
    "Gladful",
    "MOM",
    "Promill",
    "Little Joys",
    "Flurys",
    "ALOFRUT",
    "B Natural",
    "Storia",
    "Real Fruit Power",
    "Schmitten",
    "Millettree",
    "Dietfest",
    "Manna",
    "Honeyman",
    "Nature's Nectar",
    "Himalayan Natives",
    "Natureland",
    "Paushtaa",
    "Abbie's",
    "Darbo",
    "Ong's",
    "Moi Soi",
    "Happa",
    "Aptagrow",
    "Hanuta",
    "Adidas",
    "Ajmal",
    "Amulspray",
    "Aqualogica",
    "Arata",
    "Axe",
    "Baby Organo",
    "Banetion",
    "Bath & Body Works",
    "BBLUNT",
    "Beardo",
    "Bella Vita",
    "Biolage",
    "Biotique",
    "Blue Heaven",
    "Bombay Shaving Company",
    "Carmesi",
    "Cetaphil",
    "Chicco",
    "Chik",
    "Cinthol",
    "Clinic Plus",
    "Closeup",
    "Colgate",
    "Colorbar",
    "COSRX",
    "Denver",
    "Dettol",
    "Dexolac",
    "Dot & Key",
    "Dove",
    "Dr. Sheth's",
    "Emami",
    "Engage",
    "Everteen",
    "Everyuth",
    "Faces Canada",
    "Fiama",
    "FirstCry (Firsthug)",
    "Fogg",
    "Forest Essentials",
    "Foxtale",
    "Garnier",
    "Gillette",
    "Godrej",
    "Hamam",
    "Head & Shoulders",
    "Himalaya",
    "Huggies",
    "Indulekha",
    "Innisfree",
    "Johnson & Johnson",
    "Johnson's",
    "Jovees",
    "Joy",
    "Kama Ayurveda",
    "Kesh King",
    "Khadi",
    "Kiehl's",
    "Kotex",
    "L'Oréal",
    "L'Oréal Professionnel",
    "Lacto Calamine",
    "Lakme",
    "Laneige",
    "Lifebuoy",
    "Littles",
    "Lotus Herbals",
    "LuvLap",
    "Lux",
    "MAC",
    "Mamaearth",
    "MamyPoko",
    "Mancode",
    "Margo",
    "Matrix",
    "Maybelline",
    "MCaffeine",
    "Medimix",
    "Mee Mee",
    "Meera",
    "Meswak",
    "Minimalist",
    "Morphe",
    "Mustela",
    "Mysore Sandal",
    "Nasobuddy",
    "Nike",
    "Nivea",
    "Old Spice",
    "Oral-B",
    "Palmolive",
    "Pampers",
    "Pantene",
    "Parachute",
    "Park Avenue",
    "Pee Safe",
    "Pepsodent",
    "Philips Avent",
    "Pigeon",
    "Pilgrim",
    "Plum",
    "Plush",
    "Pond's",
    "Revlon",
    "Rexona",
    "Santoor",
    "Schwarzkopf",
    "Sebamed",
    "Sensodyne",
    "Set Wet",
    "Sirona",
    "Soulflower",
    "Stayfree",
    "Sugar Cosmetics",
    "Sunsilk",
    "Tedibar",
    "The Body Shop",
    "The Derma Co",
    "The Face Shop",
    "The Man Company",
    "The Ordinary",
    "TRESemmé",
    "Ustraa",
    "Vaseline",
    "Wella",
    "Whisper",
    "Wild Stone",
    "Wow Skin Science",
    "Yardley",
    "Ratna Sagar",
    "Navneet",
    "Mother Sparsh",
    "IFB",
    "Fisher-Price",
    "SuperBottoms",
    "Good Knight",
    "Aveeno",
    "Lifelong",
    "Nautica",
    "Bajaj",
    "Cerelac",
    "Kent",
    "NutriPro",
    "Prestige",
    "Philips",
    "Vega",
    "Wonderchef",
    "Dyson",
    "Havells",
    "Hit",
    "Odomos",
    "Mortein",
    "Eveready",
    "Saregama Carvaan",
    "Vicks",
    "Nat Habit",
    "Jockey",
    "Welspun",
    "3M",
    "Scotch",
    "Pidilite",
    "Fevicol",
    "Classmate",
    "Camlin",
    "Kangaro",
    "Apsara",
    "Nataraj",
    "Faber-Castell",
    "Pentel",
    "Pilot",
    "Reynolds",
    "Parker",
    "Cello",
    "Milton",
    "Borosil",
    "Signoraware",
    "Kuber Industries",
    "Pasabahce",
    "Uni-ball",
    "Luxor",
    "Scrikss",
    "Pentonic",
    "Linc",
    "Flair",
    "Rorito",
    "Hauser",
    "Casio",
    "Orpat",
    "DOMS",
    "BIC",
    "Khadi Natural",
    "Goli Soda",
    "Portronics",
    "Atomberg",
    "HealthSense",
    "Clorox",
    "Xiaomi",
    "Braun",
    "UrbanGabru",
    "VGR",
    "Phool",
    "Ant Esports",
    "Frosch",
    "Domestos",
    "Medela",
    "Parryware",
    "Orgran",
    "Hindalco",
    "Tulips",
    "Vector X",
    "Maped",
    "Ginni",
    "Kyoto Pencil",
    "Jayco",
    "Eurobond",
    "Kokuyo",
    "24 Mantra",
    "Aashirvaad",
    "Aesop",
    "Agaro",
    "Ajanta",
    "Akshayakalpa",
    "All Out",
    "Amrut",
    "Amrutanjan",
    "Amulya",
    "Ananda",
    "Andros",
    "Anveshan",
    "Aplomb",
    "Aqualens",
    "Archies",
    "Ariel",
    "Aristo",
    "Artonezt",
    "Ashtavinayak",
    "Azah",
    "B&B Organics",
    "Baybee",
    "Baygon",
    "Bailley",
    "Balaji",
    "Barbie",
    "Barilla",
    "Barosi",
    "Bauli",
    "Beaba",
    "Beco",
    "Bedekar",
    "Bergner",
    "Bharat Organics",
    "Bianca",
    "BigMuscles",
    "Bikaji",
    "Bikano",
    "Bingo",
    "Blue Tribe",
    "Boldfit",
    "Bonn",
    "Boost",
    "Boroplus",
    "Bosch",
    "Bounty",
    "Bournville",
    "Bournvita",
    "Britannia",
    "Bru",
    "Brustro",
    "Cadbury",
    "Camel",
    "Capalon",
    "Caresmith",
    "Carvaan",
    "Catch",
    "Cavin's",
    "CeraVe",
    "Chandrika",
    "Chheda's",
    "Chikma",
    "Ching’s",
    "Chitale",
    "Chukde",
    "Chupa Chups",
    "Ciconia",
    "Citizen",
    "Coca-Cola",
    "Coloressence",
    "Comet",
    "Cookd",
    "Cornitos",
    "Cosco",
    "Cothas",
    "Crax",
    "Cremica",
    "Cycle",
    "Dalda",
    "Davidoff",
    "Dhampur",
    "Dhara",
    "Disney",
    "Dr. Rashel",
    "Dreamland",
    "Dukes",
    "Durex",
    "D’Decor",
    "Epigamia",
    "Everest",
    "Exo",
    "Fabelle",
    "Fanta",
    "Farlin",
    "Fastrack",
    "Fem",
    "Ferrero",
    "Fevikwik",
    "Figaro",
    "Flipkart",
    "Fortune",
    "Freedom",
    "Funskool",
    "Gaia",
    "Gala",
    "Gas-O-Fast",
    "Gatsby",
    "Gemini",
    "Glen",
    "Goldmedal",
    "Gowardhan",
    "Greenchef",
    "Grenera",
    "Gripon",
    "Gritzo",
    "Gubb",
    "Guess",
    "Hajmola",
    "Hansaplast",
    "Happydent",
    "Harpic",
    "Hatsun",
    "Havmor",
    "Hawkins",
    "Head",
    "Health",
    "HealthBest",
    "Healthfields",
    "Healthkart",
    "Healthy",
    "Heart",
    "Heeva",
    "Heka",
    "Helios",
    "Hello",
    "Helper",
    "Henko",
    "Herbal",
    "Herbs&Heaven",
    "Heritage",
    "Heritage Dairy",
    "Hilton",
    "Hyfun",
    "Hyphen",
    "Iba",
    "Ikonic",
    "India Gate",
    "Intex",
    "Iodex",
    "Isabgol",
    "Isvaari",
    "ITC",
    "Jaguar",
    "Jaypee",
    "Josef Marc",
    "Kamasutra",
    "Kapiva",
    "Kaya",
    "Khetika",
    "Kinder",
    "Kindermum",
    "KitKat",
    "Kores",
    "Kraft",
    "Kuber",
    "Kurkure",
    "Kyari",
    "Kyoto",
    "Lactogen",
    "Lattafa",
    "Layer'r",
    "Letsshave",
    "Levista",
    "Lijjat",
    "Lindt",
    "Liril",
    "Little's",
    "Loacker",
    "Lotte",
    "Lotus",
    "Mangaldeep",
    "Mars",
    "Marvel",
    "McCain",
    "McVitie's",
    "Meishi",
    "Milky Mist",
    "Minute Maid",
    "Monginis",
    "Moov",
    "Mother Dairy",
    "Mothercare",
    "Mr. Munchies",
    "MyGlamm",
    "Nabati",
    "Nandini",
    "Natureland Organics",
    "Navratna",
    "Nescafé",
    "Nestasia",
    "Neutrogena",
    "Nihar",
    "Niine",
    "Nimbooz",
    "Nirosta",
    "Nongshim",
    "Nutrela",
    "NutriBullet",
    "Nuuk",
    "O3+",
    "Olay",
    "Oleev",
    "Olitalia",
    "Oliveware",
    "Om Sweets",
    "Omega",
    "Orbit",
    "Oreo",
    "Orient",
    "Oshea",
    "Oxford",
    "Oziva",
    "Pahadi Harvest",
    "Parle",
    "Parodontax",
    "Pears",
    "Pediasure",
    "Peppa Pig",
    "Perrier",
    "Pitambari",
    "Playminds",
    "Pluckk",
    "Poppik",
    "Popplop",
    "Praakritik",
    "Prasuma",
    "Pride of Cows",
    "Pril",
    "Pringles",
    "Priya",
    "Priyagold",
    "Pro Nature",
    "Pure Tree",
    "Puresense",
    "Quechua",
    "Quench",
    "Raaga",
    "Raffaello",
    "Ramsons",
    "Rasasi",
    "Raymond",
    "Real",
    "Red Rose",
    "Renee",
    "Revital",
    "Rishta",
    "Rivona",
    "Romsons",
    "Rotring",
    "Ruchi",
    "Sanfe",
    "Savlon",
    "Scalpe",
    "Sesa",
    "Shakti Bhog",
    "Shalimar",
    "Simmply",
    "Skinn",
    "Smoodh",
    "Snickers",
    "Sofit",
    "Softovac",
    "Softsens",
    "Sofy",
    "Soulfull",
    "Stabilo",
    "Stanley",
    "StarAndDaisy",
    "Staze",
    "Streax",
    "Sugarfree",
    "Suhana",
    "Sunfeast",
    "Surf Excel",
    "Tang",
    "Theobroma",
    "Threptin",
    "Thums Up",
    "Tilda",
    "Tinkle",
    "Toblerone",
    "Toni & Guy",
    "TonyMoly",
    "Twinings",
    "Two Brothers Organic Farms",
    "Tynor",
    "Unibic",
    "Ugaoo",
    "Ujala",
    "Uniball",
    "Unomax",
    "UrbanMooch",
    "VParents",
    "Vanesa",
    "Vanish",
    "Vasmol",
    "VCare",
    "Veet",
    "Vicco",
    "Vilvah",
    "Vim",
    "Vivel",
    "VWash",
    "Wagh Bakri",
    "Wai Wai",
    "Warana",
    "WickedGud",
    "Wingreens",
    "Winkies",
    "WishCare",
    "Wonderland",
    "Wrigley’s",
    "Xech",
    "Yakult",
    "Ybarra",
    "Youva",
    "Yummiez",
    "ZappFresh",
    "Zedak",
    "Zoff",
    "Zodiac",
    "AARINI",
    "AARVIKA",
    "Apple",
    "BellaVita",
    "Bioderma",
    "Brillare",
    "CANTU",
    "Deconstruct",
    "Dermafique",
    "Dermicool",
    "Dr.Rashel",
    "Fixderma",
    "Insight",
    "Johnson",
    "Kimirica",
    "Klairs",
    "Listerine",
    "Livon",
    "Morpheme",
    "Re'equil",
    "Simple",
    "Sugar",
    "The Moms Co",
    "Tresemme",
    "VLCC",
    "WOW",
    "A-One",
    "AADISATTVA",
    "AAKASH",
    "AARAMBH",
    "Alovera",
    "Aroma",
    "AromaMagic",
    "Aswini",
    "Ayush",
    "KAMA"
]